---
fixtures:
  repositories:
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    mcafee: "#{source_dir}"
